name: Add Marker
description: Submit a new map marker to be added to docs/data/markers.geojson.
title: "[Add Marker]: "
labels:
  - marker-add
body:
  - type: markdown
    attributes:
      value: |
        Use this form to request a new map marker.
        Latitude must be in -90..90 and longitude in -180..180.

  - type: input
    id: id
    attributes:
      label: Marker ID
      description: Optional unique ID. Leave blank to auto-generate (m-yyyymmdd-xxxxxx).
      placeholder: m-20260101-a1b2c3
    validations:
      required: false

  - type: input
    id: title
    attributes:
      label: Title
      description: Marker title shown in the popup.
      placeholder: Central Library
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Optional details for users.
      placeholder: Open weekdays 9am–6pm.
    validations:
      required: false

  - type: input
    id: link
    attributes:
      label: Link
      description: Optional URL for more information.
      placeholder: https://example.org/place
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Optional category used for map filtering.
      options:
        - (none)
        - community
        - education
        - health
        - infrastructure
        - parks
        - safety
        - transportation
        - other
    validations:
      required: false

  - type: input
    id: lat
    attributes:
      label: Latitude
      description: Required numeric value in range -90..90.
      placeholder: "37.7749"
    validations:
      required: true

  - type: input
    id: lng
    attributes:
      label: Longitude
      description: Required numeric value in range -180..180.
      placeholder: "-122.4194"
    validations:
      required: true

  - type: input
    id: icon
    attributes:
      label: Icon
      description: Optional icon value. Use "default" or a URL.
      placeholder: default
    validations:
      required: false
